### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i004-youcreate-front#2]
Crear el componente de Login que permita a los usuarios iniciar sesión en la aplicación. El diseño debe seguir el prototipo de UI proporcionado.
Requisitos:
Formulario de login: Incluir campos para correo electrónico y contraseña, y un botón de inicio de sesión. Validación básica: Validar el formato del correo electrónico y la longitud de la contraseña. Estilos: Asegurarse de que el componente cumpla con los estándares de diseño. Manejo de estados: Incluir estados de carga y error para informar al usuario sobre el progreso de su solicitud de inicio de sesión.

**Comment by PatriciaJK** [comment]
Ambiente: Login
ID caso de Prueba B-003
Resultado esperado: en la bandeja del e mail
Credenciales: 
Usuario: i6jj2r5j9j@zlorkun.com
Contraseña: 12345678
Pasos:

1. Ingresar al formulario login
2. colocar el correo electronico registrado
3. Dejar vacio el campo contraseña
4. Clickear el boton "Olvidaste tu contraseña
5. En el Formulario "Problemas para iniciar sesion", colocar la direccion de correo registrada
6. Al clickear el boton "enviar enlace de reestablecimiento", dicho mensaje solo contiene un codigo inutilizable, en vez de mandar el enlace de recupero de contraseña

**Comment by PatriciaJK** [comment]
Agrego evidencia

![Image](https://github.com/user-attachments/assets/d33dd0c3-386b-4a7d-a91a-53b79930fefa)

**Comment by PatriciaJK** [comment]
Ambiente: Login
Recomendacion: Poder ingresar con la cuenta de Facebook
Credenciales:
Usuario: i6jj2r5j9j@zlorkun.com
Contraseña: 12345678
Pasos:

1. Ingresar al formulario login
2. Posicionarse en la parte inferior del formulario
3. Tener el incono de Facebook que permita ingresar a la plataforma a traves de la cuenta de facebook

**Comment by PatriciaJK** [comment]
Ambiente: Login
Recomendacion: Poder ingresar a la plataforma con la cuenta de Google
Credenciales:
Usuario: i6jj2r5j9j@zlorkun.com
Contraseña: 12345678
Pasos:

1. Ingresar al formulario login
2. Posicionarse en la parte inferior del formulario
3. Tener el icono de Google que permita ingresar a la plataforma a traves de la cuenta de Google

**Comment by PatriciaJK** [comment]
Ambiente: Login
ID caso de Prueba B-011
Resultado esperado: Que el usuario se bloquee luego de varios intentos de ingreso Fallidos
Credenciales:
Usuario: [i6jj2r5j9j@zlorkun.com](mailto:i6jj2r5j9j@zlorkun.com)
Contraseña: 12345678
Pasos:

1. Estando registrado en la pagina, posicionarse en el formulario login
2. Intentar ingresar con contraseñas incorrectas al menos 7 veces
3. Visualizar mensaje de "Bloqueo de usuario"

Ajunto Evidencia del mensaje que envia la pagina, aun habiendo ingresado
![‌gresos varios fallidos](https://github.com/user-attachments/assets/875e23ab-802d-406f-812f-225354a21c52)

**Comment by Assalea09** [comment]
este bug queda fuera del alcance del mvp, asi que sera catalogado como "prueba pendiente" en la documentacion
