### ISSUE TITLE
Connexion endpoint Login

### ISSUE THREAD

**Issue by elianisdev** [IgrowkerTraining/i004-youcreate-front#25]
Conectar endpoint de login de acuerdo a lo entregado por los compañeros de backend

**Comment by Assalea09** [comment]
Ambiente: registro y acceso a cuenta.
Navegadores: firefox, chrome, microsoft edge.
ID casos de prueba (ejecutados): CPF-001, CPF-005, CPI-002, CPC-001, CPC-002.

Resultado esperado: los datos deben ser guardados correctamente.

Resultado obtenido: los datos se guardan correctamente.

Credenciales:
Usuario:[i6jj2r5j9j@zlorkun.com](mailto:i6jj2r5j9j@zlorkun.com)
Contraseña:12345678

Evidencia:
https://github.com/user-attachments/assets/5ee399ee-1a14-4cbf-98ee-d0988536e75f
 ![Image](https://github.com/user-attachments/assets/e5f90430-0abe-4ae8-b246-76c7b940dbed)
