### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i004-youcreate-front#3]
Crear el componente de Register para permitir que los usuarios se registren en la aplicación. Este formulario debe alinearse con el diseño proporcionado.
Requisitos:
Formulario de registro: Incluir campos para correo electrónico, contraseña, y confirmación de contraseña. Validación de campos: Validar el formato del correo electrónico, que las contraseñas coincidan y cumplan con los requisitos de seguridad. Estilos: Asegurarse de que el componente respete el diseño de UI. Manejo de Estados: Incluir estados de carga y error para brindar feedback en el proceso de registro.

**Comment by Maria007-jpg** [comment]
Prioridad: **ALTA**
Impacto/Gravedad: **ALTA**
Título: Opciones de países
Fecha 04/12/2024
Ambiente: Registro
ID (caso de prueba): M-001
Resultado Esperado: Que te de opción a elegir varios países.
Resultado Obtenido: Sólo te da la opción de seleccionar tres países.
Pasos:
1. Web https://i004-youcreate-front.vercel.app
2. Acceder a Registrarse 
3. Llenar los datos solicitados 
4. Seleccionar país
![Image](https://github.com/user-attachments/assets/0ecab314-f8a8-4254-b8a4-29f450216d39)

**Comment by Maria007-jpg** [comment]
Prioridad: **MEDIA**
Impacto/Gravedad: **MEDIA**
Título: Características internacionales de discado de países
Fecha 04/12/2024
Ambiente: Registro
ID (caso de prueba): M-002
Resultado Esperado: Que te de opción a elegir la característica internacional de discado de cada país.
Resultado Obtenido:  No te da ninguna opción a elegir la característica internacional de cada país.
Pasos:
 1. Web https://i004-youcreate-front.vercel.app
 2. Acceder a Registrarse
 3. Llenar los datos solicitados  
 4. Ingresar número de teléfono

**Comment by Maria007-jpg** [comment]
> Prioridad: **MEDIA** Impacto/Gravedad: **MEDIA** Título: Características internacionales de discado de países Fecha 04/12/2024 Ambiente: Registro ID (caso de prueba): M-002 Resultado Esperado: Que te de opción a elegir la característica internacional de discado de cada país. Resultado Obtenido: No te da ninguna opción a elegir la característica internacional de cada país. Pasos:
> 
> 1. Web https://i004-youcreate-front.vercel.app
> 2. Acceder a Registrarse
> 3. Llenar los datos solicitados
> 4. Ingresar número de teléfono

**Comment by Maria007-jpg** [comment]
Prioridad: **MEDIA**
Impacto/Gravedad: **MEDIA**
Título: Características internacionales de discado de países
Fecha 04/12/2024
Ambiente: Registro
ID (caso de prueba): M-002
Resultado Esperado: Que te de opción a elegir la característica internacional de discado de cada país.
Resultado Obtenido:  No te da ninguna opción a elegir la característica internacional de cada país.
Pasos:
 1. Web https://i004-youcreate-front.vercel.app
 2. Acceder a Registrarse
 3. Llenar los datos solicitados  
 4. Ingresar número de teléfono

**Comment by PatriciaJK** [comment]
Prioridad: ALTA
Impacto/Gravedad: ALTA
Título: 
Fecha 08/12/2024
Ambiente: Registro
ID (caso de prueba): B-012
Resultado Esperado: La plataforma no registra usuarios con correo inexistente o malformado
Resultado Obtenido: La plataforma registra usuarios con correo inexistente o malformado
Pasos:
1. Ingresar a la pagina de registro
2. Completar todos los campos de la pagina de registro excepto email.
3. Completar correo con un email inexistente (ej: osmar%%%%667@gmail.com)
4. Verificar el mensaje que devuelve la pagina
La plataforma al registrarse devuelve un mensaje "usuario registrado correctamente" y pide verificar el correo con el codigo de acceso.

**Comment by PatriciaJK** [comment]
Prioridad: Baja
Impacto/Gravedad: baja
ID: B-026
Título: Registro de Usuario con email inexistente o malformado
Fecha 08/12/2024
Ambiente: Registro
ID (caso de prueba): B-012
Resultado Esperado: La plataforma no registra un usuario con correo inexistente
Resultado Obtenido: La plataforma SI registra usuarios con correo inexistente o malformado
Pasos:
1. Ingresar a la pagina de registro
2. Completar todos los campos de la pagina de registro excepto email.
3. Completar correo con un email inexistente (ej: osmar%%%%667@gmail.com)
4. Verificar el mensaje que devuelve la pagina
La plataforma registra al usuario y devuelve un mensaje "usuario registrado correctamente" y pide verificar el correo para el código de acceso.

**Comment by PatriciaJK** [comment]
Complementa B-012![Image](https://github.com/user-attachments/assets/c338439e-e68e-4754-8034-75d4e8a0e70f)
