### ISSUE TITLE
ForgotPassword

### ISSUE THREAD

**Issue by patrigarcia** [IgrowkerTraining/i004-youcreate-front#5]
Descripción: Crear el componente ForgotPassword que permita a los usuarios recuperar su cuenta en caso de olvidar su contraseña. Este componente debe seguir el flujo de recuperación proporcionado en el diseño, permitiendo al usuario ingresar su correo electrónico para recibir un enlace de restablecimiento de contraseña.

Requisitos:
Formulario de recuperación de contraseña: Incluir un campo para que el usuario ingrese su correo electrónico y un botón de envío. 
Validación del email: Verificar que el correo ingresado sea válido (formato correcto) y mostrar mensajes de error en caso contrario. 
Integración con la API: Conectar el formulario al endpoint correspondiente para enviar la solicitud de restablecimiento de contraseña. Manejar posibles errores del servidor, como si el correo no está registrado, y mostrar un mensaje adecuado al usuario. 
Confirmación de envío: Mostrar un mensaje de confirmación al usuario indicando que se ha enviado un enlace de recuperación al correo proporcionado, o en su defecto, un mensaje de error si hubo un problema. 
Estados de carga y error: Implementar estados de carga (mientras se procesa la solicitud) y mensajes de error si ocurre algún problema.

Criterios de aceptación:
El usuario puede ingresar su correo y recibir un mensaje de confirmación si la solicitud fue exitosa. Los errores se manejan y muestran de manera clara, especialmente si el correo no es válido o no está registrado.

**Comment by PatriciaJK** [comment]
Ambiente: Login
ID caso de Prueba B-003
Resultado esperado: en la bandeja del e mail
Credenciales:
Usuario: i6jj2r5j9j@zlorkun.com
Contraseña: 12345678
Pasos:

Ingresar al formulario login
colocar el correo electronico registrado
Dejar vacio el campo contraseña
Clickear el boton "Olvidaste tu contraseña
En el Formulario "Problemas para iniciar sesion", colocar la direccion de correo registrada
Al clickear el boton "enviar enlace de reestablecimiento", dicho mensaje solo contiene un codigo inutilizable, en vez de mandar el enlace de recupero de contraseña

Adjunto Evidencia:
![reporte en github no recupera contraseña](https://github.com/user-attachments/assets/cd7b653e-c32f-43d0-b153-b4cd56458afc)

**Comment by PatriciaJK** [comment]
Ambiente: Login
ID caso de Prueba B-003
Resultado esperado: en la bandeja del e mail
Credenciales:
Usuario: [i6jj2r5j9j@zlorkun.com](mailto:i6jj2r5j9j@zlorkun.com)
Contraseña: 12345678
Pasos:

Ingresar al formulario login
colocar el correo electronico registrado
Dejar vacio el campo contraseña
Clickear el boton "Olvidaste tu contraseña
En el Formulario "Problemas para iniciar sesion", colocar la direccion de correo registrada
Al clickear el boton "enviar enlace de reestablecimiento", dicho mensaje solo contiene un codigo inutilizable, en vez de mandar el enlace de recupero de contraseña



![reporte en github no recupera contraseña](https://github.com/user-attachments/assets/de6d930a-eadf-4095-aaf7-9ef2500df44c)

**Comment by PatriciaJK** [comment]
![reporte en github no recupera contraseña](https://github.com/user-attachments/assets/6fec9961-af64-4412-af4f-79d55843ac4f)

**Comment by PatriciaJK** [comment]
![reporte en github no recupera contraseña](https://github.com/user-attachments/assets/9f0e940a-93eb-4262-b512-07aa85fc1ad8)
