### ISSUE TITLE
LandingPage

### ISSUE THREAD

**Issue by GNNZLV19** [IgrowkerTraining/i004-youcreate-front#9]
Desarrollar la landing page siguiendo los requerimentos preestablecidos y las bases de figma.

 La plataforma
contará con una landing page informativa donde los usuarios podrán conocer todas
las funcionalidades y beneficios que ofrece, junto con una sección de registro y
login que garantiza la máxima seguridad a través de encriptación de datos y
medidas de protección avanzadas,

**Comment by Assalea09** [comment]
Ambiente: landing page.
Navegadores: chrome.
ID caso de pruebas: B-013.
Fecha: 8/12/2024.

Resultado esperado: al ingresar al sitio web, todas las imagenes deberian visualizarse correctamente en alta resolucion.

Resultado obtenido: al ingresar al sitio web, las imagenes de la landing page se encuentran inhabilitadas.

Pasos:
1.ingresar a la pagina.
2.prestar atencion a las imagenes del inicio.

Credenciales:
Usuario:i6jj2r5j9j@zlorkun.com
Contraseña:12345678

Nota: el logo presenta el mismo error.

Evidencia:
https://github.com/user-attachments/assets/35a0b72a-4c94-4d94-bce9-55e9814c8cb3
![Image](https://github.com/user-attachments/assets/edacb2fc-a7cc-43ea-9307-844953e2469a)


Estatus: resuelto.

la landing page fue reestructurada y actualizada completamente, por lo cual los casos y pruebas relacionadas con ella se haran de nuevo encima de los cambios hechos.
